version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    expose:
      - "5000"
  backend:
    build: ./backend
    ports:
      - 3000:3000

volumes:
  node_modules:
